### ISSUE TITLE
While running the wikitas.py this error is showing:

### ISSUE THREAD

**Issue by aakiliqbal** [Yik-Wee/wikitas#1]
![image](https://user-images.githubusercontent.com/62759233/206862518-e7e80b7d-893a-4e8a-9318-86d98ed3954e.png)

**Terminal:**
Traceback (most recent call last):
  File "d:\Projects\python\wikitas\wikitas.py", line 37, in <module>
    callback: Optional[Callable[str, str]] = find_path_simple_parallel
  File "C:\Users\aakil\AppData\Local\Programs\Python\Python39\lib\typing.py", line 866, in __getitem__
    raise TypeError(f"Callable[args, result]: args must be a list."
TypeError: Callable[args, result]: args must be a list. Got <class 'str'>

**Comment by pixo2000** [comment]
i also have this error
